### ISSUE TITLE
Problems getting this to work with Bookworm

### ISSUE THREAD

**Issue by mightyoakbob** [PeteManchester/MediaPlayer#104]
Hi Pete,

Hope you're well.

A new RaspberryPi OS has been released.
Raspberry Pi OS Lite

    Release date: October 10th 2023
    System: 32-bit
    Kernel version: 6.1
    Debian version: 12 (bookworm)
 
With it comes a new version of mpd 0.23.12 and a new version of Java 17.0.8. 

Needless to say this has completely broken everything.
Things I've noticed:
The whole directory /bin and its contents has been removed. That breaks systemd as far as I can see.

Files cmdline.txt and config.txt have been moved from /boot to /boot/firmware. I found that and hopefully that's one issue sorted.

Then during the build process the line...
sudo /home/pi/mediaplayer/run.sh 
Normally gives a list of warnings and eventually starts the web server etc. now nothing happens, the command is dead.

Neither the webserver or MediaPlayer show up on the network.
Looking at the file app.properties it's obvious this file has not been used by mediaplayer.

I've been googling for info on /bin missing and systemd changes but it's just as though there is no issue, there's no information anywhere on this. I'll keep looking but I'm amazed there wasn't even anything in the release notes.

I'm stumped again.

Help!

Cheers,

Bob.

**Comment by mightyoakbob** [comment]
Hi Pete,

I have got further but it has been painful. It seems that /bin /sbin and /lib have gone virtual. That means with samba in default mode, they don't exist. I've changed Samba setting and those dirs exist again (virtually) but still nothing works.

Usually, when you issue the command 
sudo /home/pi/mediaplayer/run.sh

things start to happen and you get a long list of warnings before the webserver anounces it has started. With bookworm none of that happens, no error, no anything.

Do hope you're still around.

Thanks.

Bob.

**Comment by PeteManchester** [comment]
Hi Bob,

I must admit I have not yet tried Bookworm yet..

What happens if you do:

cd /home/pi/mediaplayer
./run.sh

Do you see any additional files that have been generated in the mediaplayer
folder, such as crash dumps (hs_errxxxxxxxx.log)?

At this stage I'm not even sure if the app.properties file is being read,
but try changing to 'log_console_level=on' to try and get more log info in
the console.

What if you run something simple like 'java -version' do you see the output
from that?

Thanks,

Pete.

**Comment by mightyoakbob** [comment]
Hi Pete,

Thanks for getting back to me.

I found a few helpful people on a raspberrypi forum who had a look at what I was doing. They read the supplement info on changing to systemd and told me that the notes were for wheezy and were out of date. In particular systemd now starts automatically. They told me I had lots of other legacy stuff I didn't need with systemd.

So I had a good look at the install instructions for mediaplayer and decided if it wasn't obvious what it did or wasn't systemd related I would take it out. This reduced my build procedure by 2/3. I then built a bullseye version using the cut down version of my notes. At first it didn't work but after a few hours of trying and adding one line back in, I got it working.

I took my new minimalist list and late last night tried it with bookworm. It worked! 3 days of trying but it worked.

What I ended up with is far shorter notes. After installing Java 11 and mpd, sorting the correct sound card driver all I have left for mediaplayer is this...

 
Copy the cleaned mediaplayer folder into /home/pi

cd /home/pi/mediaplayer     (change directory)
sudo chmod +x run.sh        (Make the run.sh executable)

sudo /home/pi/mediaplayer/run.sh

 Wait...
 WebServer should now be up on port 80 or port 8088

cd scripts/systemd
sudo install -v -m 755 mediaplayer.service /etc/systemd/system
sudo install -v -m 755 run_systemd.sh /home/pi/mediaplayer

sudo systemctl enable mediaplayer.service    (start at boot up)
  (symlink gets created here!)

sudo systemctl start mediaplayer.service

Wait !!  Give the pi some time to sort itself here.

sudo raspi-config
 1S4 Hostname    set as required.
 6A1 Expand Filesystem
 reboot on exit.

All Done !!

-----------------------
That works even with bookworm. Took a lot of work to get there though and so much legacy thrown away. Things like....

sudo install -m 755 -T mediaplayer.init /etc/init.d/mediaplayer

sudo install -m 755 -T mediaplayer.sh /usr/local/bin/mediaplayer

Edit the /boot/cmdline.txt adding  
   ' init=/bin/systemd' to the end without the ''.

And other stuff besides.

I don't really know what stopped it working with bookworm but something did and I cleared it. The upside is that I learnt quite a bit.

May I humbly suggest an instructions revision on the website might be in order now.

If my notes help - please use them.


Thanks

Bob.
