### ISSUE TITLE
Issues with Linn Kazoo.

### ISSUE THREAD

**Issue by Ghuru42** [PeteManchester/MediaPlayer#34]
First, great work! found this project today and it just so good!
Been working on upmpdcli for a couple of weeks but been hitting one wall after another with issues when used with Kinsky or Kazoo. MediaPlayer is just way better!

I'm using this on a raspberry B+ with the Hifiberry Digi+ card and mpd as a player. Playback via upnp works perfect, but as always there are a few issues. :-)

* Custom inputs does not show up in Kazoo, only in Kinsky.. This is a biggie for me..
* Small point on the doc about inputs, add a not that pin number as wireingPi nr and not gpio numbers.
* Kazoo sometimes don't see any source, this makes it just display the "settings" tile.
* The source "upnp" is named the same as "friendly name", this makes matching to "source input" brake if the user changes the units name. The "upnp" source should better be named "UpnpAV" as it is in Linn system.
* The Custom input module would benefit from having an option to "stop" the previous source when changing source. I have a custom source defined, that is selected by gpio. When this source is selected I would like the previous source to be stopped, for example mpd or radio.
* airplay/songcast does not play properly, read the note on how java plays sound and it does not work ok with the hifi berry :-( Airplay sometimes work, popping and glitches for 4-10s and then ok sound, skipping to different song often breaks the connection. When airplay stops it gives 100% system load and a reboot is needed to recover. Songcast plays a few seconds and then dies.

I will use a DSP for among other volume control. That device will be the master volume. I can send up/down to it so that should be easy to use the Lirc plugin and just use a different cmd line argument. But I also want to return the current volume level back to the upnp client.. Just as it works when mpd returns volume level. So I need a way to give the "lirc plugin" the current volume so it can create the volume event back to upnp clients. Could this be added??

**Comment by Ghuru42** [comment]
Hi.

I’m back again, at last..
Been way to many other things going on so have had no time to work on this.

But:
* I have switched to the new B2 board
* Latest raspian, fresh install.
* Latest mpd version compiled on the B2 from source.
* wireing pi installed and working from the cmd line, gpio util.
* Latest beta version of mediaplayer
* Hifi berry Digi+

Java is:
- - -
root@gplayer:/usr/local/bin# java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) Client VM (build 25.0-b70, mixed mode)
- - -

From this:
* Kazoo works as a charm, everything plays including all flac and wav files.
* Have not found anything that behaves bad in kazoo, source, airplay and so on works fine.

But.
* Airplay does not work, as before.
* gpio control does not work, nothing happens on the gpio pins.

Airplay:
I have not tested the analog (3.5mm) output, only the hdmi and digi+.
Digi+ gives some scrap noice, then silence.
Hdmi nothing.
With both Digi+ and Hdmi enabled the Digi shows up as plughw:0,0 and the hdmi as hw:1,1.
Setting mpd to use hw:1,1 gives full sound for upnp music, but still no airplay, tried all hw: and plughw: combos..
Debug log dont seam to indicate anything wrong from what I can see.
Any suggestions on how to proceed?

gpio:
Is anything else needed than wireing pi? It’s installed as described on the wireing pi homepage.
The gpio worked on the B+ but I cant remember if I installed any additional software for it to work.
gpio util on the cmd line works for the led,s and they use the same numbering as on the B+.

Cheers, Johan

**Comment by Ghuru42** [comment]
Did some more tests.

Noticed the java was pointing to v8, fixed so that mediaplayer runs with v7 oracle-java7 as per web info.

Booted the new SD card on a B+ board, without the Digi+ board, and removed the dtoverlay param in config.

Got both HDMI and 3,5mm output connected.
mpd is set to hw:0,0, plays fine, outputs on hdmi port.
mediaplayer is set to plughw:0,0 (also tried hw:0,0)
Still no sound from MacBook, iPhone or iPad for airplay.

I laso tried to shutdown mpd, just to test that the soundcard was not busy for any other reason.

/J

> 21 mar 2015 kl. 22:30 skrev Johan Winäs <johan@databeredning.se>:
> 
> Airplay:
> I have not tested the analog (3.5mm) output, only the hdmi and digi+.
> Digi+ gives some scrap noice, then silence.
> Hdmi nothing.
> With both Digi+ and Hdmi enabled the Digi shows up as plughw:0,0 and the hdmi as hw:1,1.
> Setting mpd to use hw:1,1 gives full sound for upnp music, but still no airplay, tried all hw: and plughw: combos..
> Debug log dont seam to indicate anything wrong from what I can see.
> Any suggestions on how to proceed?

**Comment by PeteManchester** [comment]
Hi Johan,

Can you send me your

app.proprties file
A clean log file from startup where you attemp to AirPlay, set the log
level to debug

Cheers,

Pete

**Comment by Ghuru42** [comment]
Se attached files.

run.sh is modified, se attached.

debug.log has:
* start with ”run.sh | tee debug.log”
* wait for debug output to show startup completed.
* enable airplay on my iPhone5S
* play local track (itunes sync)
* disabled airplay
* start kazoo
* play a track
* pause track
* close kazoo
* stop mediaplayer


> 22 mar 2015 kl. 10:42 skrev PeteManchester <notifications@github.com>:
> 
> Hi Johan,
> 
> Can you send me your
> 
> app.proprties file
> A clean log file from startup where you attemp to AirPlay, set the log
> level to debug
> 
> Cheers,
> 
> Pete
>
