### ISSUE TITLE
Lumin app

### ISSUE THREAD

**Issue by stabilo--** [PeteManchester/MediaPlayer#35]
Hi,

First, thanks for this mediaplayer - a perfect companion for my ds.

There's only a problem with the Lumin app (ipad) that does not always display the now playing informations (songs info, elapsed time...) and never display the informations when the playlist was "launched" by another app (kinsky, kazoo).

I also have two questions about controlling the player 
Is il possible with the alarm plugin to play a specific / saved playlist ?
Is il possible to get information on how to send play / stop commands for home automation integration (Command line / JSON / is the player compatible with LPEC ?)

Thanks for your reply ! (and sorry for my approximative english)

**Comment by PeteManchester** [comment]
Hi,

For the ability for an alarm to play a specific playlist have a look at this app developed by Barry:

https://github.com/bazwilliams/upnp-playlist-service

That should meet your requirements.

Cheers,

Pete.

**Comment by stabilo--** [comment]
Hi,
thanks i will give it a try.

cheers,
F.

2015-04-15 11:12 GMT+02:00 PeteManchester <notifications@github.com>:
