### ISSUE TITLE
Playlist support

### ISSUE THREAD

**Issue by andrum99** [PeteManchester/MediaPlayer#40]
Apologies if this is the wrong place to ask this: I am looking for an OpenHome player that allows shared playlists to be stored on the player. This mediaplayer seems to work really well on my Raspberry Pi, but shared playlists would be really useful. At the moment I can use a single current playlist, but creating shared playlists in Kazoo or Kinsky does not seem to be possible. Is this feature supported?

**Comment by PeteManchester** [comment]
Hi,

Thanks for trying MediaPlayer.

It's a good question about shared Playlists, and I've been thinking about it, but I don't think the renederer is the best place to implement shared playlists.

There is no OpenHome api for the renderer that would support shared playlists, and if I was to save a playlist on a renderer the other renderers are not aware of that Playlist.

For me the best place to implement shared playlists is a combination of the Control Point and MediaServer functionality.

Kinksy and Linn Songbox support shared playlists
https://oss.linn.co.uk/trac/wiki/SongboxManual#SharedPlaylist

I have Songbox installed just to support shared playlists, but Kinksy is being replaced soon by Kazoo so I will have to look for an alternative soon.

It looks like Kazoo CP has just started supporting local Playlists, but as yet unfortunately no shared playlists as yet.

This project looks very interesting, you can create playlists and schedule them to play at certain times, so it might be possible to add functionality to play the playlist as well as schedule one to play..

https://github.com/bazwilliams/upnp-playlist-service

Thanks for your suggestion,

Pete.

**Comment by andrum99** [comment]
Thanks for the speedy reply. I did a bit more reading on the subject after I posted my original message and you are right - it seems what I actually need is an openhome media server that implements the ohPlaylistManager service. Kazoo Server looks promising but as yet there is no Raspberry Pi version and there is no source code available (at least, not that I can find).
