### ISSUE TITLE
Pi4j does not init, beta and release.

### ISSUE THREAD

**Issue by Ghuru42** [PeteManchester/MediaPlayer#43]
In the debug log I find:
2015-04-27 10:25:26,999 [main] DEBUG [org.rpi.os.OSManager] This is a Raspi so Attempt to initialize Pi4J
Looking in the source this row comes from OSManager.java, where there is a note about the new Pi4JManager.java, and that the Pi4J init is commented out. It seams that the new Pi4JManager never gets called as none of the debug lines from that code is in the debug log.

Result is that the InputSources GPIO actions does not work.
Tested on Pi2 B with Digi+ card.
GPIO works fine with the gpio cmd line utility, using the pin number defined in InputSource.xml

**Comment by PeteManchester** [comment]
Hi,

Can you send me the full log file and a description of what is not working on the InputSources plugin.

You are right that I moved the code from the OSManager for the Pi4JManager, I should remove the log message, but the Pi4JManager is called from the InputSorucesImpl and LCDDisplayImpl.

Thanks,

Pete.

**Comment by Ghuru42** [comment]
Se attached file.
Row 174 for the old debug output.
Can’t find the debug rows from the new init anywhere.
The InputSources are read since I get my extra source input in kazoo.

**Comment by PeteManchester** [comment]
The attachment didn't arrive, can you email it to pete.hoyle1@gmail.com

**Comment by PeteManchester** [comment]
Do you have the CustomInputSource plugin installed (CustomInputSource.jar)?
https://github.com/PeteManchester/MediaPlayer/wiki/Plugins---Input-Selector

I don't see any reference to this in your log file

2015-04-27 12:57:15,616 [main] INFO  [org.rpi.os.OSManager] Start of LoadPlugins
2015-04-27 12:57:15,792 [main] INFO  [org.rpi.os.OSManager] End of LoadPlugnis

**Comment by Ghuru42** [comment]
I did more tests but never managed to the the gpio function to work on the Rpi2 with the Cirrus card installed. I resorted to using the LIRC plugin and just add cmd line args there to set the gpio, works just fine.
