### ISSUE TITLE
AirPlay volume.

### ISSUE THREAD

**Issue by Ghuru42** [PeteManchester/MediaPlayer#45]
On Linn systems the volume work like this:
IR / upnp/ Kazoo controls the Master/output volume.
AirPlay has it's own "input level" volume.
So when using AirPlay you can set the "max volume" you want to play with ir/kazoo and then use your iPhone for minor level changes.
This makes a lot of sense since you can not set your phones airplay volume before pressing play, it will still be in "ringtone". So if you had your headphones in set to 90% volume you are in for a surprise when the Linn Exakt system runs at volume 90.

For me this would be the desired way mediaplayer should work as well.
For this I think there need to be an option for the already present "java sw volume" to always be enabled, even when a hardware volume is present.
With this option enabled AirPlay and SongCast has it's own "input level".

**Comment by PeteManchester** [comment]
Can you explain a bit more about how that would work in the following scenarios.

If you set the volume to 50 in Kazoo and then started Airplay which had a volume of 90% would the volume stop at 50 in Kazoo.

Again if you had the volume set to 50 in Kazoo and started Airplay which was set to 100%  and then decreased the volume in Airplay what should happen? Would Kazoo stop at 50 or would it decrease?

If you had Kazoo set to 50 and Airplay set to 50, what happens if you increase the Airplay volume

**Comment by Ghuru42** [comment]
With the option enabled AirPlay/Songcast never touches the volume level set to/from upnp/mpd.
It always uses the sw volume for the java soundcard, no matter what mpd,s respons is, just as if mpd reported -1 as volume.

A ”normal” setup would be to use mediaplayer with say a DAC card, that has a volume.
Mpd sees this volume and you can control volume in kazoo, and AirPlay.
This analog signal is feed to a amp, this amp has a volume nob, you use this to set the max volume your system can do.
In this setup neither Kazoo and AirPlay has a control over the final volume, this i the nob,s job :-)

With the Linn system the ”master” volume is controlled by the upnp system, it's the volume nob on the amp.
This master volume can be set by upnp/kazoo/IR or push buttons on the front of some amps.
Starting kazoo you see what the volume is set to, if it’s to high, you can lower it before pressing play.
The AirPlay is just an input with it’s own sw level/gain control, it can not affect the volume nob/master volume.
Why, well when you start iTunes or Spotify on an iPhone over AirPlay, you can not se what volume will be set.
If you used Spotify with headphones to work, set to 90% this is the volume AirPlay will use.
If AirPlay could effect the master volume you would be in for an event, volume 90 on a Linn Exact system is LOUD!

If you look at how a AirPort or AppleTv works it’s the same.
The volume on the iPhone after starting Spotify affects the spdif output or the hdmi output. 
This goes to your amp, where you have the master volume control.
AirPlay can not touch you volume nob, it can only change it’s line level as a source.

My system is like the Linn system.
Mediaplayer used mpd, that reports a volume control of 0-100.
This volume level is the master nob. There are no other volume controls after this.
At volume 100 it’s line level right into the power amp, that has no gain control.
This works just perfect with kazoo/upnp, just as with the Linn system.
But with AirPlay I can only guess what volume level I had on headphones/AirPlay last.

With this option my system will behave just as Linn,s system does. :-)

/J

**Comment by Ghuru42** [comment]
SongCast can however work as it is :-)
Since this has a proper volume nob that reflects the master volume..

/J

**Comment by PeteManchester** [comment]
I've just uploaded a new beta version.

https://github.com/PeteManchester/MediaPlayer/tree/master/com.upnp.mediaplayer/download/beta

Try this and let me know what you think.

If your DAC does not support Hardware volume control then set

java_sound_software_mixer_enabled=true

Otherwise set it to false.

Let me know what you think..

**Comment by Ghuru42** [comment]
Hi.

Finally found time to get back to this project.

It works Perfect!

/Johan

**Comment by imgrant** [comment]
I've just come across this issue myself, and sorry to open up old issues, but my preference would be for the other way!

If AirPlay volume is just an attenuation and the master volume is separate as this enhancement has now been implemented, for me it means that I need to have another app (Kazoo, BubbleDS, etc.) running in addition to iTunes (or whatever I am using to stream AirPlay) to be able to adjust the master volume.
Whereas if the AirPlay volume controlled the master volume (as before?), then I only need one app.

The issue of not knowing what volume AirPlay is going to output at and exposing dangerously loud volumes rears it head the other way for - if the master volume (Kazoo, etc.) is low, then when other users in my house want to increase the volume of an AirPlay stream, they will turn the analog knob on the amplifier up to compensate, then other sources (e.g. CD player) will be very loud.

Perhaps this could be a configurable option? 'AirPlay volume is linked to master volume' or not.

**Comment by Ghuru42** [comment]
I think it should be a an option, if mediaplayer uses java for airplay volume, or affects master volume.

Most users will use a normal amplifier, with a volume knob, and will want airplay to affect the master volume.
The way I use it, I need it to be a separate volume done by java, to mimic how a linn system works.

/johan

**Comment by PeteManchester** [comment]
I've added a new config option  'airplay_master_volume_enabled'. 
If 'true' changing the AirPlay volume will update the master volume (for Ian)
If set to false changing the AirPlay volume will only change the Airplay volume and not update the Master Volume (for Johan)
Default value is true..

**Comment by Ghuru42** [comment]
Nice!

/J

**Comment by imgrant** [comment]
Lovely to have personalised settings! :-) I will try it out soon.
