### ISSUE TITLE
Problem with Soundcast volume

### ISSUE THREAD

**Issue by andrum99** [PeteManchester/MediaPlayer#46]
Since rebooting my Pi 2 running MediaPlayer on Raspbian, which was previously updated to the latest software using apt-get, I have a problem with the volume control in the Songcast app on my Windows laptop. The problem is that the volume is shown as 0, even though it is actually set to 94, as it should be. (This is because my HifiBerry DAC+ produces distortion when I set it to 100%). At one point this prevented me from using Songcast, but I discovered that if I played something using Kazoo first, then used Songcast, then the Songcast playback worked fine.

To complicate things, I have also recently reinstalled my laptop, including installing, then removing Kaspersky Total Security which does strange things to the network. I don't think this has anything to do with it, but it might.

I noticed in the scrolling log that appears in the MediaPlayer Web UI that my system is reporting messages like this:

2015-05-27 15:00:23,840 [Thread-12] DEBUG [org.rpi.player.PlayManager] Volume is less than Zero, assume the DAC doesn't support Hardware Volume Control

I don't know if it was reporting these before though. Any help would be appreciated.

**Comment by andrum99** [comment]
Some more information on this. I have noticed, when setting my pi with a slightly different setup on a different SD card (same Pi) that when I have the audio output configured to use the default built in audio device (in this case HDMI) the volume control works fine. When I switch to using the HifiBerry DAC+ the volume control goes wonky. So it looks like something in a recent change has caused MediaPlayer to no longer recognise the volume control on my HifiBerry DAC+ card.

**Comment by PeteManchester** [comment]
So just to clarify, is it just that the volume control in your Songcast app on your windows laptop is not updating with volume changes?

Does Kazoo and or Kinsky update with the volume changes?

Can you change the volume of the Songcast playback using Kazoo and or Kinsky?

The HifiBerry DAC does not implement a Hardware volume control and so mpd.conf needs to be configured with mixer_type "software" and for Songcast/Airplay the mediaplayer needs to have the option
java_sound_software_mixer_enabled=true

**Comment by andrum99** [comment]
Kazoo also shows the volume level as zero.

I have applied the configuration changes that you suggested to mpd and MediaPlayer and I now have volume control back. Strange that I did not need these settings before.

Is the volume control that this software is now using the same volume control that is accessed by amixer?

**Comment by PeteManchester** [comment]
Good to hear it's now working, not sure how it was working before..

The volume control for Airplay and Songcast is a software volume control implemented in MediaPlayer, for mpd I suspect that is also a software volume control implemented in mpd.

Does the amixer volume control work with the HifiBerry DAC? I thought it did not support hardware volume control..

**Comment by andrum99** [comment]
The amixer volume control definitely used to work with the HifiBerry DAC. I have just checked and it does not work now. I suspect that in the past ALSA was providing its own software mixer for the HifiBerry DAC, but for some reason this is no longer happening. I consider this a bug, since I would expect all sound outputs on a system to have a system level volume control. I will see what the HifiBerry people have to say.

Thanks for your help.

**Comment by PeteManchester** [comment]
ok. let me know what they have to say about the HifiBerry DAC...

I have been using the IQAudio Pi DAC+ and that supports hardware volume control..

**Comment by andrum99** [comment]
I will let you know. It definitely looks like a bug in either the Pi's software or the HifiBerry driver. The volume control for the HifiBerry DAC available in ALSA has disappeared.

**Comment by andrum99** [comment]
There seems to be a problem with the Pi's software talking to the HifiBerry DAC. Other people are reporting problems with it as well. You can close this ticket as this is not a problem with MediaPlayer.

**Comment by PeteManchester** [comment]
ok, thanks, so just to confirm, normally the DAC/Pi should support Hardware Volume control?

**Comment by andrum99** [comment]
I presume so, yes. Something is currently broken, so the debug message about the card not supporting hardware volume control looks like it is caused by the problem. I have not been able to get the HifiBerry people to tell me whether or not the card has a hardware volume control, but it should do given the DAC chip is high end and has all sorts of other controls - emergency ramp down etc.

**Comment by PeteManchester** [comment]
Q: Does it have a volume control?
A: Our new HiFiBerry DAC+ board comes with an integrated volume control.  However the older HiFIBerry DAC uses the digital data without any post-processing. It will output the sound stream with the volume the application feeds it. Many applications can use an internal volume control (so called software volume control). If the application you want to use does not have a software volume control, you can’t control the volume by software. However the best way to control the software is a analog volume control after the DAC. While software volume control is an option, it will reduce signal-to-noise ratio. If you connect the DAC to your amplifier, you should use the volume control of your amplifier.


https://www.hifiberry.com/forums/topic/dac-hardware-volume-control/

Try the following in /etc/mpd.conf

audio_output {
type “alsa”
name “Output”
device “hw:0,0″
mixer_control “Playback Digital”
mixer_device “hw:0″
mixer_index “0”
dsd_usb “yes”
}

**Comment by andrum99** [comment]
Thanks. We have not root caused it yet, but it looks to me like the mixer control that controls the volume on the HifiBerry DAC+ card is broken in the Pi. MediaPlayer and alsamixer, a console mode volume control app, are both broken in different ways. Also, other users are reporting problems with other software e.g. Volumio. HifiBerry say they have not made any changes so it is either a Pi-specific change or the mainline kernel that has gone wrong.

You can close this issue if you like, since the problem is not caused by MediaPlayer.
