### ISSUE TITLE
Source change via RESTfull interface.

### ISSUE THREAD

**Issue by Ghuru42** [PeteManchester/MediaPlayer#47]
Being able to use an IR remote to switch sources would be great.
I have already got lirc working nicely with the REST interface to do skip/prev as well as stanby.
Could we add a command to change source this way as well? Say by submitting the source name as specified in the InputSources config?

**Comment by PeteManchester** [comment]
I've added a new interface for changing the source, method name is 'changeSource' and a parameter of value=<source_name> should be set..

http://localhost:8088/myapp/mediaplayer/changeSource?value=Laptop

I've pushed it to the beta release..

**Comment by Ghuru42** [comment]
Calling the URL with a input name specified gives ”OK” back, and Kazoo shows by ”Toslink” input as active.
Calling with a bad name responds with ”Not found:…”.

But mpd did not get stopped, nor does it trigger the lirc plugin that a change source event has taken place.

I use the Lirc plugin to trigger changes to the sound card when changing sources, so when playlist is active the sound is routed from the raspberry i2s to the spdif output, and when toslink is selected it’s routed from spdif in to out.
The background to doing a source change via REST is that I can set lirc to call this url from a button, selecting toslink input. I then have two buttons that adjust the system volume. So when watching TV I just select this source and have volume control. Instead of having to open an app to select toslink as a source first. :-)

/J

**Comment by PeteManchester** [comment]
Ok, try the latest beta version, I tidied up some of the code and the source change events from the web interface are now propagated properly

**Comment by Ghuru42** [comment]
Will give it a go as soon as I get back home tonight :-)

**Comment by Ghuru42** [comment]
Works perfect!

Found another small issue :-)
I made a toggle button for play/pause/mute.
If mediaplayer is on ”Playlist” source it runs ”mpc toggle”.
If mediaplayer is on any other source it uses mute on the soundcard.
The effect is that you get a mute button that if you are playing music is pause.

The reason for the ”mpc toggle” is simply that you only have stop in the REST interface, works just as fine as you read back the play status from mpd.
To find what source is used I use the lirc plugin to call a ”setsource.sh” script, this script sets the sound card to the right mode and outputs what source is used in /run/source.
The issue is that there is a sporadic function on boot, sometimes I get ”standby”, sometimes it changes to ”playlist”.

The best solution would be to have ”toggleTrack” or ”playTrack”+”getPlayStaus”.
And a ”getSource” that returns the current source.
Then all functions can call mediaplayer and react in the right way.

/J

**Comment by PeteManchester** [comment]
I've added some more methods to the restful interface, you now have:

'setStandbyMode?value=<true or false>' - Set the StandyMode
'getStandbyMode' - Get the Current StandbyMode
'nextTrack' - Play the Next Track in Playlist
'previousTrack' - Play the Previous Track, if track has played for more than 5 secs current track is started again
'stopTrack' - Stop the Current Track
'pauseTrack' - Pauses the Current Track
'playTrack' - Plays the Current Track, if Paused will resume, if track not playing will attempt to play Next Track 
'incVolume' - Increase the Volume
'decVolume' - Decrease the Volume
'muteVolume?value=<true or false>' - Mute the Volume
'changeSource?value=<name of source>' - Change the Source
'getSourceName' - Source Name
'getPlayerStatus' - Current Status of the Player

**Comment by Ghuru42** [comment]
Perfect!

No shortcuts left :-)

Will send you an update soon on how this device works and what is does.
Next step is to get songcast transmit working :-)

Happy days! /Johan
