### ISSUE TITLE
What does the "HttpError" mean in the debug log?

### ISSUE THREAD

**Issue by Ghuru42** [PeteManchester/MediaPlayer#49]
I get these in my debug log:
--
2015-07-14 18:08:58,063 [Thread-2] INFO  [org.rpi.main.OpenHomeLogger] SSDP Multicast      HttpError
--
Is this an error? Something that needs fixing or? :-)

**Comment by PeteManchester** [comment]
I see those error messages in my log sometimes.

They are at the ohnet library level and i have never managed to workout what is happening, but I don't think it is anything to worry about..

Cheers,

Pete.
