### ISSUE TITLE
^M in the scripts

### ISSUE THREAD

**Issue by clanger9** [PeteManchester/MediaPlayer#51]
Hi Peter,

Just experimenting with your player on a Pi and I noticed that there are ^M CR/LFs in the distributed scripts (most notably, run.sh, maybe others).

I noticed you mentioned this as a possible side-effect of unzipping the files on another platform, but this is on a clone of your source (downloaded & installed on a Raspberry Pi).

It's really hard to see these on GitHub, but they're definitely there in the source if I open https://raw.githubusercontent.com/PeteManchester/MediaPlayer/master/com.upnp.mediaplayer/run.sh in a proper text editor.

Easy enough to fix up, but potentially confusing for new users. Any chance you could run a clean up on the scripts? Or I can do this if you want (I'm new to GitHub, but it looks possible to submit changes...)

Anyway, so far so good, I'll report back with any other issues if I find them.

Cheers,
Paul.

**Comment by PeteManchester** [comment]
Hi Paul,
Was that the beta or release version that you installed.
It's something I have tried to fix before and looks like I failed..

Looks like the problem is when I save from Eclipse to GitHub..

Cheers,

Pete.

**Comment by clanger9** [comment]
Hi Pete,

This is in the files in the release .ZIP and in the source tree.

I’ll have a look through and see if there are any more instances…

Cheers,
Paul.

**Comment by clanger9** [comment]
Hi Pete,

Yes, found ^M s in the two init scripts (mediaplayer.init and mediaplayer.sh) as well as run.sh.

Cleaned those up and MediaPlayer works like an absolute charm. I’ve now added multi-room capability to my Linn system, which I’m very happy about.

One suggestion: the default player ID of “Default” confused me at first - perhaps “MediaPlayer” or something more descriptive would be clearer.

Anyway, thanks for putting together such a great piece of software!

Cheers,
Paul.

**Comment by PeteManchester** [comment]
Hi Paul,

Thanks, glad you like it!!

I've pushed a new beta version where I've removed the ^M from the scripts, it was easy in the end, just needed a push to do it..

Good suggestion about the PlayerId as well, I was trying to find a name that would not clash with anything already configured..

Thanks,

Pete.
