### ISSUE TITLE
Player Intermittently spitting

### ISSUE THREAD

**Issue by mightyoakbob** [PeteManchester/MediaPlayer#52]
Hi Pete,

I wonder if you could help me please. I am a neebie to this but I have managed to get it running but I have a problem and have no idea how to fix it. Any help would be much appreciated.

I've used your MediaPlayer on a Pi2 with HiFiBerry Dac+ and the most concerning of the problems is spitting.. The player can play for 20 minutes or half an hour without an issue, then it can suddenly start spitting and sometimes it seems to jump tracks. After misbehaving like this it will then recover and play fine again until the next time. I also have a Linn Akurate DS player which is connected to th same Netgear 1Gb switch and the ADS nevers misses a beat.

Music source is a Synology DS214+ NAS and the files are flac.The NAS is connected to the same switch. There is next to no network traffic when the spitting starts. The media server is MinimServer running on the Synology.

MediaPlayer version 0.0.8.7
Java version 1.8.0
I'm sure there is more things you need to know but I can't guess what they are.

I keep thinking that this player is taking bytes out of a buffer and feeding them to the dac, so either there is a problem filling the the buffer or there is a problem emptying the buffer into the dac. Maybe the buffer needs to be larger so the player is more imune to network hickups? Not that I have any reason to think there are network problems.

Any advice/help appreciated.

Cheers,

Bob.

**Comment by PeteManchester** [comment]
Hi Bob,

What type of files are you playing, are they Hi Res 24bit 96Khz? That is the only time I have seen the revision B Pi struggle, but the Pi2 seems ok with Hi Res.

If not I would normally suspect the network, but from what you have said maybe not in your case.

What happens is that the MediaPlayer adds a track to the MPD Playlist, MPD plays that track directly from the Media Server, sending events to MediPlayer about the duration of the track and the current number of seconds played. When there is 3 seconds left (or a Stop status is sent) MediaPlayer will add the next track to the MPD playlist. So there is not much that MediaPlayer is doing when the track is playing.

You could try looking in the MPD log file to see if there is any clues in there 
/var/log/mpd/mpd.log

You could try adding some options to the mpd.conf file to change the buffer settings
/etc/mpd.conf
maybe something like:
audio_buffer_size       "4096"
buffer_before_play      "100%"

http://linux.die.net/man/5/mpd.conf

As another test you could try installing mplayer (apt-get install mplayer) and configure MediaPlayer to use mplayer, just to see if there is something with MPD, although MPD is normally very stable.

mediaplayer_player=mplayer

If none of the above work maybe try stripping back a bit and try testing without the HifiBerry Dac+, just have the output from the Pi Audio Jack and see if it still happens.

Let me know how it goes,

Pete.

**Comment by mightyoakbob** [comment]
Hi Pete,

Thanks for the help, much appreciated. I have some answers for you.

It doesn't seem to matter if the flac I play is 192/24 or 44.1/16 both spit quite happily.

I've had a look in the log you suggested (mpd.log)
It is full of:

flac: flac lost sync
flac: flac lost sync
flac: unkown flac error
flac: bad flac header

And these do link with when the spitting happens. During the 20 minutes of it playing fine, there is none of this.

I've made the change to the buffer you suggested and this seems to have reduced the probelm considerably but not cured it. It is still not really good enough to use.

All of the files play fine on the ADS and I've also run them through AudioTester.exe and it says they are fine.

Looking at this log file revealed something else. It is a lesser problem but I've not got any volume control and the mpd.log also has an error on every track which says..

Failed to open mixer for 'My ALSA Device': no such mixer control: PCM
I have not got the remotest idea what ALSA is and PCM was pulse code modulation in my younger days. I've looked on the hifi berry site and the instructions are just not spelled out enough, I can't understand them.

It says I need to make these settings but does not say how or where.

amixer sset PCM 90%
amixer sset 'PCM' 96%
amixer sset 'playback Boost' 0%

But as i say it makes no comment at all how or where to do this.

I've no doubt it is obvious if you know but useless if you don't.

Thanks again,

Cheers,

Bob.

**Comment by PeteManchester** [comment]
Hi Bob,

It's a bit clumsy, but maybe try increasing the audio_buffer_size value, to see if that will fix the problem..
What version of MPD are you using, using the command 
mpd --version

For the volume control, have a look at this wiki that andrum99 wrote.

https://github.com/PeteManchester/MediaPlayer/wiki/Fixing-volume-control-for-PCM5122-based-sound-cards-with-Raspbian-builds-5--5--2015-and-later

The changes are needed in the /etc/mpd.conf file.

You should be able to see the mixer names if you enter the command.
alsamixer

Cheers,

Pete.

**Comment by mightyoakbob** [comment]
Hi Pete,

Fixed the volume control, it was the 'Digital' setting I'd not seen that before. Thanks for the pointer.

I took my pi/berry to work today. The intention was to disconnect the berry from the pi and set the dac settings back to on board. Then to bring it home this evening for a long test. I connected it up at work and tested it playing from work's NAS Synology DS110J but again running minimserver.

Got it going and then thought I would just leave it running and see what happened. I left it playing all day on hi-res and not one single glitch, nothing, log as clean as a whistle.

Got it home, connected up started it playing from my nearly new super NAS Synology DS214+ MinimServer. It lasted 37 minutes and then broke down spitting something auful.

So, I went into our office room upstairs (spare bedroom really) and switched on an older NAS a Synology DS111 running MinimServer. This is connected directly to my router and not my main switch, so it is double hop to get to the players on the main switch.

Connected like this it has now played for 3 hours and 20 minutes without a blip.

Bin the new NAS I hear you say but...

It will play with my Linn ADS and/or Sonos all day without any sign of a problem. In fact this is the very first hint that something is wrong with it.

So it is now equal between the NAS and the pi. Both work fine with anything else but the two together and it's good night.


Please have a brilliant idea. :-)


Cheers,

Bob.

**Comment by PeteManchester** [comment]
Hi Bob,

Sorry, no brilliant ideas at the moment...

Just a guess, but could it be a  faulty port on the switch or a faulty network cable for your NAS. Maybe the Linn ADS is more resilient to network problems. Just a guess though..

Cheers,

Pete.

**Comment by mightyoakbob** [comment]
Hi Pete,
It seems that my Pi2 has a problem when connected to a fast NAS via any 1Gb switch. However, place an old 100Mb switch anywhere in the chain and the pi plays fine for hours. It is as though the speed negotiation between pi and 1Gb switches doesn't work properly ot my pie cannot actually cope with its advertised speed. Very odd but I have found it works amazingly well via a USB WiFi dongle even at 192/24.

Cheers,

Bob.

**Comment by PeteManchester** [comment]
Thanks Bob, most strange, I would never have thought of that...

Who would have thought a Wifi dongle would perform better than a 1Gb switch :-)

Cheers,

Pete.
