### ISSUE TITLE
would like to know how to use alsaequal for output

### ISSUE THREAD

**Issue by ghost** [PeteManchester/MediaPlayer#54]
Hi. I can't find an email address for you Pete, so I'm doing as suggested on the MediaPlayer website and filing a bug against MediaPlayer. I am trying to get MediaPlayer working with the alsaequal graphic equaliser plugin. I have managed to mpd to send its output to alsaequal, so tracks played from Kazoo as going via the graphic, but I can't figure out how to get MediaPlayer's internal output to go to alsaequal. I have tried using "equal" and "plug:alsaequal" as the soundcard suffix but these don't work. Can you help?

**Comment by PeteManchester** [comment]
Can you send details of how you configured mpd to use alsaequal?
Also can you send me the mediplayer log files from start up including when you try to use either airplay or songcast.

**Comment by andrum99** [comment]
mpd is configured with this in the /etc/mpd.conf file:

```
audio_output {
        type            "alsa"
        name            "My ALSA EQ"
        device          "plug:plugequal"
        mixer_device    "default"
        mixer_control   "PCM"
        mixer_index     "0"
}
```

I deleted the mediaplayer.log file so I could send you a "clean" log file without having to go in and edit it. Unfortunately it doesn't seem to be producing a log file now. I will try with the latest version of mediaplayer later.

**Comment by andrum99** [comment]
I have had another look at this. The issue seems to be that MediaPlayer is set to play to a "card". Since the graphic equalizer is a plugin, it is always bypassed by MediaPlayer's internal player. The solution would be for MediaPlayer to support sending its output to what I believe is called an alias, for example pcm.!default, as defined in /etc/asound.conf.
