### ISSUE TITLE
AirPlay sometimes dies??

### ISSUE THREAD

**Issue by Ghuru42** [PeteManchester/MediaPlayer#55]
I have had a few times where AirPlay has stopped responding.
To test I have used two apps in iOS, SSDPtester and "Air Discovery". 
SSDP tester sends a SSDP discovery message and prints all packets replied. From these I can see that the unit respons to a lot of other services, but not AirPlay.
"Air Discovery" tells me the same, the unit is there but just not saying the "remote speaker" option.
Restarting mediaplayer sorts the issue and AirPlay is once again available.

Not sure if this is in Mediaplayer as such, can be that the upnp replay/discovery is just down..
Either way I need some guidance on how to verify what went wrong where when this happens, as it does not happen often. It much more common that the AirPlay sub system on iOS or osx failes and iOS or osx needs a reboot.

Any suggestions?

**Comment by PeteManchester** [comment]
Not sure on that one, have you had a look at the mediaplayer logs around the time when Airplay drops off the network?

I've updated the jmdns library to the latest version if you want to test that, not sure if it will make a difference though..
