### ISSUE TITLE
Junk CTRL+M characters in mediaplayer/scripts/systemd/run_systemd.sh

### ISSUE THREAD

**Issue by ghost** [PeteManchester/MediaPlayer#57]
While setting up MediaPlayer on Raspbian Jessie I noticed that run_systemd.sh still contains CTRL+M characters. It might be worth checking the rest of the shell scripts as well. ;-)

**Comment by PeteManchester** [comment]
Ok, thanks will have a look. I thought I had got rid of them all :-(

**Comment by DoomHammer** [comment]
[.gitattributes](http://git-scm.com/docs/gitattributes) might come in handy.
