### ISSUE TITLE
Radio service Read action should take Id as parameter, takes index

### ISSUE THREAD

**Issue by medoc92** [PeteManchester/MediaPlayer#59]
As the subject says. Read should accept a preset Id parameter:
http://www.openhome.org/wiki/Av:Developer:RadioService#Read
but it accepts an index into the ids array instead.

**Comment by PeteManchester** [comment]
Thanks, I hadn't noticed that.
I guess most control points are using the 'ReadList' method, which CP were you using that used the 'Read' method?

I just pushed a new version that fixes this.

**Comment by medoc92** [comment]
PeteManchester writes:
 > Thanks, I hadn't noticed that.
 > I guess most control points are using the 'ReadList' method, which CP were you
 > using that used the 'Read' method?
 > 
 > I just pushed a new version that fixes this.

I am updating upplay (http://www.lesbonscomptes.com/upplay/) to support the
OpenHome Radio Source, and I just noticed this while trying out the
different actions.
