### ISSUE TITLE
tunein support seems to be broken

### ISSUE THREAD

**Issue by andrum99** [PeteManchester/MediaPlayer#60]
The URL http://opml.radiotime.com/Browse.ashx?&c=presets&partnerid=a valid partner ID&username=a valid username&formats=mp3,wma,wmvideo,ogg,hls&render=json is returning a 403 error all of the time. This prevents MediaPlayer from getting a user's preset list from TuneIn.

It is possible that I am running up against a limit on the number of calls which can be made to this URL. TuneIn apparently limits the number of calls to its API, even if you use a valid partner ID.

**Comment by PeteManchester** [comment]
I just tried it and it works for me, if I use an invalid PartnerId then I get the http 403 error, so it would suggest that your PartnerId is not correct.

**Comment by andrum99** [comment]
OK, thanks. I reckon that is what is happening. I was using the one from the Kodi plugin and assumed it was valid. I did think when it failed that it might be invalid. Feel free to close this bug. I will need to try and get a valid partner ID from somewhere.
