### ISSUE TITLE
Source switch on radio selection

### ISSUE THREAD

**Issue by gwin-zegal** [PeteManchester/MediaPlayer#62]
Hello,

I noticed that the "source selection" of MediaPlayer does not switch to radio when playing a radio, tested on BubbleDS. When testing this on a DS Majik, the source switches to radio automatically when it stays on Playlist on MediaPlayer

A minor issue, I admit...

Thank you for the great SW!
Emmanuel

**Comment by PeteManchester** [comment]
Thanks Emmanuel..

Can you tell me how to recreate the problem? 
I don't have BubbleDS but I tested with Kazoo and when I change the source on one instance of Kazoo it is updated on the other instances of Kazoo..

**Comment by gwin-zegal** [comment]
Hello,

in fact, it is not reproducible under Kazoo, Kinsky, Songbook because you have to first select the source then the station for a radio for example. 

In BubbleDS, there is a fetching of the station list and a special tab to look at the list without switching the source. Not that bad in fact, Linn should think about that. By clicking on a station list, the linn majik switches automatically to radio source even if a playlist is being played; selecting a musique file from a library switches from radio mode to playlist mode. Only with BubbleBS reproducible unfortunately...
With Mediaplayer, the radio in playlist mode is being played but the source stays unchanged. Same behavior when loading a file in radio mode. 
I hope I was clear enough, I am not native english speaking...

Emmanuel

**Comment by PeteManchester** [comment]
Hi Emmanuel,

I've created a new version that now should change the source of Bubble DS is used as the control point.

The new version can be found here: 

https://github.com/PeteManchester/MediaPlayer/releases/tag/v20160316

**Comment by gwin-zegal** [comment]
Hello,

I tested and it work like awaited with Songcast/Radio/Playlist. Thank you very much!!

Kind regards,
Emmanuel
