### ISSUE TITLE
Would like to know how to switch off multiroom feature in beta version

### ISSUE THREAD

**Issue by andrum99** [PeteManchester/MediaPlayer#64]
Can you possibly tell me how to switch off the multiroom feature so it doesn't show up in Kazoo when using the current beta version of MediaPlayer?

**Comment by PeteManchester** [comment]
Hi,

In the app.properties set the option 'mediaplayer_enable_receiver' to 'false' and restart MediaPlayer

**Comment by andrum99** [comment]
Thanks. I've updated my repo with a comment to that effect.
