### ISSUE TITLE
Suggestions : send playlist status to other DS

### ISSUE THREAD

**Issue by gwin-zegal** [PeteManchester/MediaPlayer#65]
Hello, a small suggestion/feature for future dvpt: in my configuration, I have three "rooms" and as I do not seat always in the same room, I goes sometimes from one to another and wants to hear further the music in another room. For that purpose, I need to refill the playlist from the other DS or activate multiroom. I'll find a nice feature to send the status/playlist from one DS to another, include stop/play at the same position.

Thank you for the great SW! 
kind regards,
Emmanuel

**Comment by PeteManchester** [comment]
Hi Emmanuel,

Thanks for the good suggestion.

It is a good suggestion, but it is more the role of the Control Point to manage the playlist and even copy it to another DS. 

From what I remember I think Bubble DS Control point had this functionality, not sure about the continue to play from same position though.

Hope this helps,

Pete.

**Comment by gwin-zegal** [comment]
Hello Pete,

thank you for your answer. Yes, you're absolutely right (shame on me!)... this is 100% a control point issue. I will look further in BubbleDS.

Emmanuel
