### ISSUE TITLE
Mediaplayer not running on latest Jessie

### ISSUE THREAD

**Issue by guussie** [PeteManchester/MediaPlayer#69]
Hi Pete,

I have been rebuilding a system based on the latest Raspbian Jessie and I keep getting error messages as below:

Start error message ----------
pi@ClassikN:~/mediaplayer $ sudo java -jar mediaplayer.jar
Jun 07, 2017 7:24:26 AM org.glassfish.jersey.server.ApplicationHandler initialize
INFO: Initiating Jersey application, version Jersey: 2.6 2014-02-18 21:52:53...
Jun 07, 2017 7:24:28 AM org.glassfish.grizzly.servlet.WebappContext deploy
INFO: Starting application [Coment] ...
Jun 07, 2017 7:24:28 AM org.glassfish.grizzly.servlet.WebappContext initServlets
INFO: [Coment] Servlet [org.rpi.web.longpolling.LongPollingServlet] registered for url pattern(s) [[/playerstatus]].
Jun 07, 2017 7:24:28 AM org.glassfish.grizzly.servlet.WebappContext deploy
INFO: Application [Coment] is ready to service requests.  Root: [/grizzly-comet].
Jun 07, 2017 7:24:28 AM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [0.0.0.0:80]
Jun 07, 2017 7:24:28 AM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
Unable to determine hardware version. I see: Hardware	: BCM2835
,
 - expecting BCM2708 or BCM2709. Please report this to projects@drogon.net
pi@ClassikN:~/mediaplayer $ 
End error message-------------

In the forums people seem to suggest that this could be related to a problem for p4j and the fact that the latest kernel is not supported..

wiringpi was updated to work with the latest Jessie, apparently.

Is there a way to save this problem?

Other info that may be relevant below.

Thanks, Guus

pi@ClassikN:~ $ gpio -v
gpio version: 2.44
Copyright (c) 2012-2017 Gordon Henderson
This is free software with ABSOLUTELY NO WARRANTY.
For details type: gpio -warranty

Raspberry Pi Details:
  Type: Pi 3, Revision: 02, Memory: 1024MB, Maker: Sony 
  * Device tree is enabled.
  *--> Raspberry Pi 3 Model B Rev 1.2
  * This Raspberry Pi supports user-level GPIO access.
pi@ClassikN:~ $ 

pi@ClassikN:~ $ uname -a
Linux ClassikN 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux
pi@ClassikN:~ $

**Comment by PeteManchester** [comment]
Hi Guus,

If you download the [pi4j 1.2 snapshot](http://get.pi4j.com/download/pi4j-1.2-SNAPSHOT.zip)

And then replace the existing  pi4j-core.jar in the mediaplayer_lib directory with the new version.
Then restart mediaplayer and that should solve your problem.

Cheers,

Pete.

**Comment by guussie** [comment]
Hello Pete,

That fixed it!

Thanks, Guus
