### ISSUE TITLE
Expose API

### ISSUE THREAD

**Issue by arjunmenon** [PeteManchester/MediaPlayer#70]
Hey
Is there an API to work with plugins? Exposing an API would be nice and allow for extending the system with other languages.

**Comment by PeteManchester** [comment]
Hi,

Sorry about the long delay...

There is a limited RESTful API, the details are here:

https://github.com/PeteManchester/MediaPlayer/wiki/RESTfull-Interface

Hope this helps,

Pete.

**Comment by arjunmenon** [comment]
Hey
I was asking about the plugins - https://github.com/PeteManchester/MediaPlayer/tree/master/com.upnp.mediaplayer/plugins

I would like to extend the system with more sources. So if you had an API which it can hook to, so that the output of a plugin can directly be piped into the application.

**Comment by PeteManchester** [comment]
If you wanted to you could develop your own plugin in Java.  

Here is the source code for the current plugins:

https://github.com/PeteManchester/MediaPlayer/tree/master/com.upnp.mediaplayer/src/org/rpi/plugin
