### ISSUE TITLE
Support for Tidal and Qobuz?

### ISSUE THREAD

**Issue by Dual01** [PeteManchester/MediaPlayer#73]
Dear Pete,
congratulations to this great piece of software. At the moment, I use the bubble UPNP server software together with the mediaplayer to stream from Tidal, the lumin software is the control point. In order to simplify the system, it would be great if an access option to Tidal or Qobuz could be implemented into mediaplayer. Is this possible with a reasonable effort?

**Comment by PeteManchester** [comment]
Hi,

Thanks, I had briefly thought about adding support for Tidal and/or Qobuz but haven't really had time.

There are a number of things that would need to be considered:
To develop against the Tidal or Qobuz API a developers key is needed, I would need to get one, but int theory that should be ok.
Determine if MPD or MPlayer could play the music stream that is provided by Qobuz and Tidal.
I would need an account with one or both to test.

So it's not a definite no, but I've not got any plans to do an integration.

Thanks again,

Pete.

**Comment by seroper** [comment]
Pete,

Just to say that I would really like to see Tidal integrated.  Kazoo is much easier to use than BubbleDS so if mediaplayer could be upgraded so  Linn recognise it as latter firmware and Tidal works that would be great!

I don't have a lot of time either, but would be happy to help with your guidance.

Regards
Simon

**Comment by Dual01** [comment]
Hi Simon,
btw, you can install the bubble upnp server software in your network system. This software provides access to Tidal. Then, you can use Tidal with the mediaplayer software as renderer and with Kazoo as control point.
Best regards
Dieter

**Comment by seroper** [comment]
Hi Dieter,

Thanks for the tip, I didn't know that.  Do you configure the mediaplayers renderers as openhome players in bubble server config?  Any recommended links for setup?

Thanks
Simon

**Comment by Dual01** [comment]
yes. The bubble upnp server software can be installed on any system (e.g. PC, raspberry etc) in your network. The installation procedure is on the respective web site. Its function is to add openhome functions to streamers (renderers). The second function is that it provides Tidal and/or Qobuz access for streamers. In principle, the mediaplayer has already built in openhome functionality so you would not need bubble upnp server for this purpose but it also adds Tidal access for the mediaplayer. Thus, you simply have to add the mediaplayer to the renderer list of the bubble upnp server. You can control your music playing either with Kazoo or with the Lumin software (which is my favorite).
Have fun with it. It is a great software.

**Comment by guussie** [comment]
Hi Dieter,

I got bubbleupnp server running all right. The only renderer it sees is my Majik and I can indeed add Qobuz/Tidal support. It does not see the java mediaplayer based renderers. Do you have any suggestions? I have a Qobuz trial subscription and the objective is to get native Tidal/Qobuz support from my several java mediaplayer renderers. At the moment I am using a workaround, which is to play the Qobuz stream on my Majik and then streaming from there to the java renderer. Thanks!

**Comment by Dual01** [comment]
Hi Guussie,
I run the BubbleUPNP server and the mediaplayer as service. Mediaplayer has to be running to be seen by the BubbleUPnP server. Then, you should see all the mediaplayer devices in the renderer list of the BubbleUPNP server. Then, you just have to create an openhome renderer on the BubbleUPNP server for Tidal access. I guess all the components have to be in the same home network.
I did this with several RPis. It always worked.

**Comment by guussie** [comment]
Hi Dieter,

All my RPi's are on the same home network and I can see all through Kazoo.

I am currently running BubbleUPNPSErver from the command line for testing and I see the following:

> 	Manufacturer: Linn Products Ltd
	Model name: Majik DS-I
	UDN: 4c494e4e-0026-0f21-935e-012396190171

	[main (1)                    ] INFO     - 0:00:16.41     - d                           : added Renderer device: 		Living:UpnpAv
	[cling-11 (73)               ] INFO     - 0:00:16.138    - c                           : 

So BubbleUPNP creates its own version of the renderer. Qobuz works through this version.

I can also see the Majik DSi in the renderer list on the BubbleUPNP server page.

BubbleUPNP also sees my media server (MinimServer).

Then, in Terminal, I see the following:

> 	Manufacturer: Made in Manchester
	Model name: Open Home Java Renderer: v0.0.9.1
	Model description: 'We Made History Not Money' - Tony Wilson..
	Presentation URL: http://127.0.1.1:80
	UDN: device-Classik-Classik-MediaRenderer
	[cling-36 (100)              ] INFO     - 0:05:27.9      - f                           : Sending device descriptor retrieval message: (c) GET http://192.168.1.46:52821/device-Library-Library-MediaRenderer/Upnp/device.xml
[cling-39 (107)              ] INFO     - 0:05:27.80     - c                           : 

	Manufacturer: Made in Manchester
	Model name: Open Home Java Renderer: v0.0.9.3
	Model description: 'We Made History Not Money' - Tony Wilson..
	Presentation URL: http://127.0.1.1:80
	UDN: device-Library-Library-MediaRenderer

	[qtp14299293-105 (105)       ] INFO     - 0:06:13.732    - b                           : com.bubblesoft.bubbleupnpserver.server.servlets.f-13d5094: g
	[qtp14299293-105 (105)       ] INFO     - 0:06:13.736    - d                           : removed comet session: auicmhuslqkknrzf5whhdq4z
	[qtp14299293-105 (105)       ] INFO     - 0:06:13.739    - d                           : added comet session: auicmhuslqkknrzf5whhdq4z
	[cling-39 (107)              ] INFO     - 0:07:39.966    - f                           : Sending device descriptor retrieval message: (c) GET http://192.168.1.28:52821/device-MiniDSi-MiniDSi-MediaRenderer/Upnp/device.xml
	[cling-36 (100)              ] INFO     - 0:07:40.25     - c                           : 

	Manufacturer: Made in Manchester
	Model name: Open Home Java Renderer: v0.0.9.1
	Model description: 'We Made History Not Money' - Tony Wilson..
	Presentation URL: http://127.0.1.1:80
	UDN: device-MiniDSi-MiniDSi-MediaRenderer

	[cling-39 (107)              ] INFO     - 0:10:03.3      - f                           : Sending device descriptor retrieval message: (c) GET http://192.168.1.29:52821/device-Bathroom-Bathroom-MediaRenderer/Upnp/device.xml
	[cling-42 (112)              ] INFO     - 0:10:03.81     - c                           : 

	Manufacturer: Made in Manchester
	Model name: Open Home Java Renderer: v0.0.9.0
	Model description: 'We Made History Not Money' - Tony Wilson..
	Presentation URL: http://127.0.1.1:80
	UDN: device-Bathroom-Bathroom-MediaRenderer


These are the RPi players in my network. But they don't show up in the Renderer list on the server web page.

This really puzzles me. Could it have something to do with different Java versions?

Pete, any idea of what could be happening?

Thanks, Guus

**Comment by Dual01** [comment]
Hi Guussie,
just to be sure that we mean the same thing. You have to actively add your renderers to the BubbleUPnP server list. To do this, you launch a web browser on a PC or iPad in your network, e.g. firefox, google chrome, Safari... (it does not work for me with Microsoft edge) and type in the address line  http://localhost:58050  where "localhost" has to be replaced by the exact network address of the device where the BubbleUPnP server is running. Then, you should see the bubble upnpserver web page on your browser. 
Then, you might disable internet access, go to the media renderers tab where you should see the list of your renderers. Then you have to activate each RPi renderer separately in order to create the corresponding bubbleUPnP-mediated renderer.
Maybe this helps

Dieter

**Comment by guussie** [comment]
Hi Dieter,

Yes, we are talking about the same thing. The only renderer I see is my Linn Majik DSi, to which I can add Qobuz support. The mediaplayer renderers I can't see.

I have also set up a Volumio player, just to test. The Volumio player (renderer) is visible.

When I run an openhome mediaplayer on my Mac, it is not visible in the renderer list.

Very strange.... I think I have tried this in the past and it worked, but then I did not have a Qobuz (trial) account, haha!

Thanks for your help!

Guus

**Comment by guussie** [comment]
I finally figured out how to get all this to work. In the Config, you have to enable the AVTransport. I normally always disable this.

So now all seems to work!

**Comment by guussie** [comment]
I have created comprehensive instruction on my Wiki: [https://github.com/guussie/PiDS/wiki/12.-Tidal-and-Qobuz-integration-through-Bubbleupnpserver](url)

**Comment by guussie** [comment]
I have added comprehensive installation instructions on my Wiki: [https://github.com/guussie/PiDS/wiki/12.-Tidal-and-Qobuz-integration-through-Bubbleupnpserver](url)
