### ISSUE TITLE
Alarm clock and playlists

### ISSUE THREAD

**Issue by seroper** [PeteManchester/MediaPlayer#74]
Hi,

Could you please help me to get going with the alarm clock plugin?
How do I specify which playlist to play when the alarm goes off?  Where does the playlist have to reside?  I'd like to play both locally stored songs, or Tidal streamed songs.

Many thanks
Simon

**Comment by PeteManchester** [comment]
Hi Simon,
Unfortunately the Alarm Plugin is not that sophisticated, when it plays a 'PlayList' it just plays the tracks that  are in the current players PlayList.

If you want the ability to create and schedule playlists have a look at this project created by Barry:

https://github.com/bazwilliams/upnp-playlist-service

Thanks,

Pete.

**Comment by seroper** [comment]
Thanks for the help Pete, appreciated.
