### ISSUE TITLE
Playback control

### ISSUE THREAD

**Issue by winxi01** [PeteManchester/MediaPlayer#76]
Hi, many thanks for this nice and very useful piece of software! It runs without any issues on my pi 3 b+.
I've just a question: is there a(n easy) way to apply playback controls (i.e. play/pause/next track/previous track) from the command line at the raspi itself. If this were possible, I'd implement hardware buttons and/or an IR remote to control playback.

**Comment by PeteManchester** [comment]
Hi, thanks for your kind comments.

There is a RESTful API that could be used from some control functions, have a look here:

https://github.com/PeteManchester/MediaPlayer/wiki/RESTfull-Interface

Thanks again,

Pete.

**Comment by winxi01** [comment]
This is awesome, thank you so much!
Just for reference, if somebody other stumbles across this: the wiki page linked above seems to be outdatet. There are more commands available - use http://rpipi2.local:8088/myapp/mediaplayer/help to see the full list.

**Comment by PeteManchester** [comment]
Thanks, I've updated the wiki :-)
