### ISSUE TITLE
No GENASubscription Events send on Linux (Ubuntu 20.04)

### ISSUE THREAD

**Issue by ik666** [PeteManchester/MediaPlayer#79]
Hi,

I've one issue with GENASubscription Events on Linux (Ubuntu 20.04 x64). I'm able to register to all published events (I receive a 200 - OK), however the caller never get's notified of any events (neither OH nor AvTransport) by MediaPlayer.

On an armv7 systems everything works just fine.

IK

**Comment by PeteManchester** [comment]
Hi,
Can you describe in more detail what it is you are trying to do.

Try setting the following options in the app.properties (and restart) to see if that gives you any clues as to why the client is not receiving the events:
openhome_log_level=All
log_file_level=debug

Pete.

**Comment by ik666** [comment]
Hi Pete,

thanks for the debug tip! Seemed to be some port conflict. I've changed the `openhome_port`, and now I receive all events, just as I do on an armv7 system.

IK

**Comment by ik666** [comment]
I've finally figured out what had happen. It wasn't a port issue. If you configure a friendly name with a whitespace character like `mediaplayer_friendly_name=media renderer` no events will be submitted from MediaPlayer to the control point. The device descriptor has some mal formatted URL's (icon-tags), but the `eventSubURL` looks actually good. I had no issues with other renderer containing whitespace chars, so I think this might be some `MediaPlayer` issue but I'm nut sure yet. Just in case you want to follow up this issue I reopend the ticket, so  feel free to close it ...

I'll be one week off ... 

IK

**Comment by PeteManchester** [comment]
Hi,
I tested this on Raspi and I can still subscribe for events when the Friendly name contains a whitespace character:

![image](https://user-images.githubusercontent.com/3873447/91836775-28d17100-ec43-11ea-8352-b9e2a6f7d4a7.png)

**Comment by ik666** [comment]
OK, then this look more like an issue on my side. Thanks for checking back!
