### ISSUE TITLE
code formatter for eclipse

### ISSUE THREAD

**Issue by ik666** [PeteManchester/MediaPlayer#85]
Hi there,

is it possible for you to add an eclipse code formatter profile to you MediaPlayer repository?

Cheers

IK

**Comment by PeteManchester** [comment]
Added Eclipse code formatter export to directory structure.
 EclipseFormatProfileLongLine.xml 

It is the standard Eclipse Profile with Line Wrapping\Maximum Line Width set to 9999

**Comment by ik666** [comment]
Thanks.
