### ISSUE TITLE
Playlist.play() doesn't play playlist

### ISSUE THREAD

**Issue by ik666** [PeteManchester/MediaPlayer#86]
Hi,

I've one issue with OpenHome services, where I do not know, what the best solution might be. 

1) Insert songs to playlist
2) play a radio station (by calling setid() & play() on RadioService)
3) call PlaylistService.play()

-> nothing happens. Playlist will not be played.

4) call PlaylistService.pause()

-> RadioStation pauses

5) call PlaylistService.play()

-> RadioStation resumes

According to the OH docs : http://wiki.openhome.org/wiki/Av:Developer:PlaylistService#Play

> If TransportState is Stopped or Paused, start playing the track indicated by the Id state variable.
> If TransportState is Playing or Buffering, re-start playing the current track from the beginning.
> If the Playlist source is not active, deactivates the current source and activates Playlist.
> Disables Standby in the Product service if that was enabled (and if the product is controllable over the network in this mode).

I think after step 3 the following should happen:

- ProductService should active Playlist as current source
- MediaPlayer should play the last played playlist item. In the example above no track has been played yet, therefore it should start with the first song ... 

The point is: 

PlayManager.play() is unaware which source is currently active, and therefore makes the wrong decision. PlayManager might track the "EventSourceChanged" event to track the current source, or just read the current source from ProductService  (but it's hard to acquire a SimpleDevice handle to get the info) and call PlayManager.playThis() with a playlist channel? 

or since PlayManager already has own methods for (almost) each service (playAv(), playRadio(), playAirPlayer(), etc.)  a new method (maybe something like PlayManager.playPlaylist() could be added which PrvPlaylist calls ?

Cheers

IK

**Comment by PeteManchester** [comment]
Hi,

Can you explain a bit more about what you are trying to do?

Is this from the Control point that you are trying to this? Or from some
custom code you are writing?

Looking at how Kinsky and Kazoo do this, they use the Seek Index of the
PlayList Provider where the value is the index of the track to be played
(zero is the first track).
This will change the source to PlayList and start the track playing.

[image: image.png]

Cheers,

Pete.

**Comment by ik666** [comment]
I write a custom control point and implement the functionality just by reading the official docs. I know this makes it difficult for  you to reproduce the issue. I'll push my code soon. 

For the user experience I intend to implement a functionality, to switch between input sources, just like you would do on a regular hardware device. "Pressing" Radio-Button should play the last selected radio station, "Pressing" Playlist-Button should resume playing the playlist. "Pressing" Network-Button could/should  resume to stream/play last AVTransportUri, etc. 

Sure I could implement the seekid method for playlist for playing a playlist, and remember the last played Playlist ID to resume playback, or when switching back to radio to remember the last played Radio-ID, but if the services (Radio / Playlist / etc.) would implement play() as documented, it would be much nicer :)

**Comment by ik666** [comment]
I have a solution ... I'll work on this.

**Comment by PeteManchester** [comment]
Sorry I didn't see that you had already implemented a fix, I just pushed a new version that fixes Play for the PlayList and Radio Providers.
Have a look and see what you think.

Thanks,

Pete.

**Comment by ik666** [comment]
I've checked your commit. It (almost) works, but when the playlist is deleted and new items are added. I just deleted one conditional statement and now it seems to work fine. Thanks! I have reverted my commit, and provided a small fix on master. 

Maybe you can start a "project" for this repo, so we have a workboard to synchronize?
