### ISSUE TITLE
Rest Interface enhancement

### ISSUE THREAD

**Issue by Koala887** [PeteManchester/MediaPlayer#93]
Thanks for the great software. I use the player as a house radio on a Rpi. To switch the radio stations on, I use a button and the radioNextChannel command of the Rest interface. but that only works until you get to the end of the radio list. would it be possible to start again at the beginning of the list after the last channel?

**Comment by PeteManchester** [comment]
Hi,
Thanks for the feedback..

I've modified RESTful methods radioNextChannel and radioPreviousChannel  to cycle round when they reach the end of the list .

I've pushed a new version that Github at:

https://github.com/PeteManchester/MediaPlayer/tree/master/com.upnp.mediaplayer/download/beta

Please can you test and let me know if it's ok..

Pete.

**Comment by Koala887** [comment]
It works. Thank you!
