### ISSUE TITLE
Control point (Linn Kazoo) shows track name where artist name should be

### ISSUE THREAD

**Issue by andrum99** [PeteManchester/MediaPlayer#95]
I've got a strange issue with the current beta of MediaPlayer. The problem is that on my control point (Kazoo), on both Windows and Android, I'm seeing the track name twice - where it should be in the track name field, and also directly below that in the artist field. The problem seems to be caused by MediaPlayer, since switching to the release version of MediaPlayer fixes the problem. I've attached a screenshot which illustrates the problem - in the middle of the screen is a popup showing the list of players. In this list, the currently playing tracks are correctly shown with track name and artist - I'm guessing Kazoo is using the track info from the playlist directly. At the bottom left of the screen is the 'currently playing' info, which shows the duplicated track name where the artist name should be. This is also shown if you click on the 'currently playing' info to bring it full screen.

![mediaplayer-beta-issue](https://user-images.githubusercontent.com/58046090/121246724-5e258200-c899-11eb-9982-195439ba4914.png)

**Comment by PeteManchester** [comment]
Hi,
Can you try the latest beta version I've just uploaded, it should fix this issue.

Thanks,

Pete.

**Comment by andrum99** [comment]
> Hi,
> Can you try the latest beta version I've just uploaded, it should fix this issue.
> 
> Thanks,
> 
> Pete.

That has fixed it - many thanks 😀
