### ISSUE TITLE
Player shows in Linn Kazoo and Kinsky but not Lumin or BubbleUPnP

### ISSUE THREAD

**Issue by mightyoakbob** [PeteManchester/MediaPlayer#98]
I had a go at this a few years ago and gave up because of networking issues with both ethernet and wifi. Decided to have another go now hoping the newer Buster OS would fix my issues. Things are a bit different from the instructions but I've got Linn Kazzo and Kinsky to send music to the player and it works. Biggest change is insserv. Has to be installed and gives errors galore when you try to use it. Gave up on that and swapped to using systemd instead and that works fine.

Could do with some help or advice to get the ipad control point 'Lumin' to see the player and the same for BubbleUPnP which is running on my NAS. Both not seeing the player.

Not sure if this is important but if I...
sudo /home/pi/mediaplayer/run.sh
I get:
log4j:WARN No appenders could be found for logger (io.netty.util.                                   internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more in                                   fo.

I don't understand this at all.
Thanks for any help and for the whole project.
Cheers,

Bob.

**Comment by PeteManchester** [comment]
Hi Bob,

Thanks...

Agreed, for Buster OS it is best to use systemd rather than insserv, 

https://github.com/PeteManchester/MediaPlayer/wiki/Using-'systemd'--for-the-MediaPlayer-service-controller

I need to update the docs.


For your Lumin and BubbleUPnP problem, can you check the app.properties file to see what is set for the option:

mediaplayer_enable_avTransport

If not set to true, try setting it to true and restart mediaplayer.

Possibly Lumin and BubbleUPnP need the avTransport provideder to be enabled.

Thanks again,

Pete.

**Comment by mightyoakbob** [comment]
Hi Pete,
Thanks for the quick response and suggestion.

mediaplayer_enable_avTransport was set to false and changing it to true did make it appear in BubbleUPnP Server as a renderer but most regretably, it did NOT work for Lumin.

Have you any other thoughts or possibilities? Lumin does see both real Linn players and BuBBleUPnP server fudged ones.

I could get BubbleUPnP to do its thing and use that to enable Lumin but that defeats the object of having an OpenHome player.

Looking at the app.properties file a little more I can't see anything else that might obviously be involved but did notice a line that looked a bit odd or even wrong to me

mplayer_path=/usr/bin/mplayer

There is no file or folder  /usr/bin/mplayer  
    but there is a file..
mplayer_path=/usr/bin/mpd

Don't know if that's significant.

I've got a set of notes I've made on how to make Buster play for Kazoo in the simplest way. If you want them, give me a shout.

Thanks again for your help.

Bob.

**Comment by mightyoakbob** [comment]
A little more information:
I tried a Micro SD card I built in 2015 and it did boot and Lumin could see it! Didn't expect that. The mediaplayer.log file says this is version 0.0.8.8. Of course that was with a different OS and java version and mediaplayer version.
Daft question...
Using samba on the new build that cannot see lumin, could I delete the folder /home/pi/mediaplayer and replace it with older versions, starting with 0.0.8.8 I know works?

I've also noticed the new faulty build/version is giving a continuous stream of errors you can see this on the webpage.:
eg.
 2021-09-21 16:25:32,400 [EventThread] DEBUG [org.rpi.pins.PinManager] Reconnect Attempt: io.socket.client.socket@42b0a6

Also in mediaplayer/mediaplayer.log I have this...
2021-09-21 16:30:00,983 [main] WARN  [org.rpi.os.OSManager] Using full_path /home/pi/mediaplayer/mediaplayer_lib/ohNet/linux/armv6hf
2021-09-21 16:30:02,025 [main] ERROR [org.rpi.pins.PinManager] Error Reading from File: pins.json
2021-09-21 16:30:02,038 [main] ERROR [org.rpi.providers.PrvPins] Error Reading from pins.json
java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50)
	at org.json.JSONTokener.<init>(JSONTokener.java:94)
	at org.json.JSONArray.<init>(JSONArray.java:162)
	at org.rpi.providers.PrvPins.updatePins(PrvPins.java:162)
	at org.rpi.providers.PrvPins.readPins(PrvPins.java:156)
	at org.rpi.providers.PrvPins.<init>(PrvPins.java:86)
	at org.rpi.main.SimpleDevice.initSimpleDevice(SimpleDevice.java:195)
	at org.rpi.main.SimpleDevice.<init>(SimpleDevice.java:101)
	at org.rpi.main.StartMe.main(StartMe.java:80)

Help!

Thanks,

Bob.

**Comment by mightyoakbob** [comment]
Hi Pete,

I hope you see this Pete because I've put days of work into this and I've broken down the problem of Lumin.
I have a 2015 prepared micro sd card that works fine but was unable to get a current card to work. To find out why I took the long route..

Using the same base throughout of:
Raspberry pie + 2021-05-07-raspios-buster-armhf-lite.img
samba
Java 8
mpd
I tried installing a range of releases of mediaplayer.
20-10-2015   v20151020       tested - Lumin works
05-02-2017   v20170205       tested - Lumin works
20-03-2018   v0.0.9.3            tested - Lumin works
30-04-2019   v0.0.9.4            tested - Lumin does not work !
20-05-2019   v0.0.9.5            tested - Lumin does not work !
It looks to me as though something was changed for v0.0.9.4 that stopped Lumin seeing the player.

Maybe due to using Buster it seems we now have to also use "systemd".
This means the two files inside /home/pi/mediaplayer/scripts/systemd are now needed and both are full of ascii char 13 or hex 0d. These could do with being removed in the distribution.

Also, the file mediaplayer/scripts/systemd/mediaplayer.service has a line in it..
ExecStart=/opt/mediaplayer/run_systemd.sh
This conflicts with the instructions and I got mine working by changing that line to what the instructions say ie;
ExecStart=/home/pi/mediaplayer/run_systemd.sh

I hope you find this helpful and can at some point check out what was done that broke Lumin in 2019.

I don't think I can get any further without some help.

Thank you 

Bob.

**Comment by PeteManchester** [comment]
Hi Bob,

Thanks for the work you have done.

I'm busy at work at the moment, when I get time I will have a look to see why MediaPlayer is not working with Lumin, looking at the changes I made for v0.9.4, there a quite a few, so i will have to work through them..

For the files being full of ascii 13 chars, that's an ongoing battle that I don't seem to be winning, I will try again, it's not ideal but somewhere in the wiki are instructions on how to clean up the files..

Thanks again,

Pete.

**Comment by PeteManchester** [comment]
Hi Bob,

I had a look and think I have fixed it.

Can you test with this beta version please:

https://github.com/PeteManchester/MediaPlayer/tree/master/com.upnp.mediaplayer/download/beta

Lumin does not support the PrvProduct v2, so I have downgraded to PrvProduct v1.

Thanks,

Pete.

**Comment by mightyoakbob** [comment]
Hi Pete,

Yes indeed, the test version you sent to me does indeed work fine with Lumin.

That's impressive Pete, well done and thank you. Will that version become the new "Latest Release" ?

I've had so much practice at building an SD card for this from scratch that I can do it now in around 1 hour, so if you need another test just shout.

Thanks again.

Bob.
